package simplebankingsystem2;


import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
*/

/**
 *
 * @author rhed
 */



public class Menu extends javax.swing.JFrame {
    
    public static Menu Instance;
    public static double accountOne = 500.0;
    public static double accountTwo = 500.0;
    
    public static HashMap<String, Double> accounts = new HashMap<>();
    
    static{
        
        accounts.put("123456789", accountOne);
        accounts.put("987654321", accountTwo);
        
    }
    
    public Menu() {
        initComponents();
        Instance = this;
        
        CalculatorTxtField.setEditable(false);
        CalculatorTxtField2.setEditable(false);
        AccountInfo.setEditable(false);
    }

    
    public void setBalanceAccountOne(double Balanceone) {
        this.accountOne = Balanceone;
    }
    
    public void setBalanceAccountTwo(double Balancetwo) {
        this.accountTwo = Balancetwo;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DepositButton = new javax.swing.JButton();
        TransferButton = new javax.swing.JButton();
        WithdrawButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AccountNumber = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        AccountBalanceLabel = new javax.swing.JLabel();
        AccountNumberBalance = new javax.swing.JLabel();
        ViewAccountLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ViewButton = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        ViewPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AccountInfo = new javax.swing.JTextArea();
        WithdrawPanel = new javax.swing.JPanel();
        CalculatorTxtField = new javax.swing.JTextField();
        nine = new javax.swing.JButton();
        EnterButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        six = new javax.swing.JButton();
        two = new javax.swing.JButton();
        one = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        three = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DepositPanel = new javax.swing.JPanel();
        CalculatorTxtField2 = new javax.swing.JTextField();
        nine2 = new javax.swing.JButton();
        EnterButton2 = new javax.swing.JButton();
        ClearButton2 = new javax.swing.JButton();
        eight2 = new javax.swing.JButton();
        seven2 = new javax.swing.JButton();
        six2 = new javax.swing.JButton();
        two2 = new javax.swing.JButton();
        one2 = new javax.swing.JButton();
        four2 = new javax.swing.JButton();
        five2 = new javax.swing.JButton();
        three2 = new javax.swing.JButton();
        zero2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TransferPanel = new javax.swing.JPanel();
        TransferAmount = new javax.swing.JTextField();
        TransferNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ConfirmTransfer = new javax.swing.JButton();
        ViewAccountLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        DepositButton.setText("Deposit");
        DepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositButtonActionPerformed(evt);
            }
        });

        TransferButton.setText("Transfer");
        TransferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferButtonActionPerformed(evt);
            }
        });

        WithdrawButton.setText("Withdraw");
        WithdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Account Number:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));

        AccountNumber.setForeground(new java.awt.Color(0, 0, 0));
        AccountNumber.setText("#");

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        AccountBalanceLabel.setForeground(new java.awt.Color(0, 0, 0));
        AccountBalanceLabel.setText("Account Balance:");

        AccountNumberBalance.setForeground(new java.awt.Color(0, 0, 0));
        AccountNumberBalance.setText("0.0");

        ViewAccountLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ViewAccountLabel1.setForeground(new java.awt.Color(0, 0, 0));
        ViewAccountLabel1.setText("Banking System");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("$");

        ViewButton.setText("View All Accounts");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AccountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addGap(35, 35, 35))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(AccountBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AccountNumberBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                        .addComponent(TransferButton, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                        .addComponent(DepositButton, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                        .addComponent(WithdrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                        .addComponent(ViewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(ViewAccountLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AccountNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountBalanceLabel)
                    .addComponent(jLabel7)
                    .addComponent(AccountNumberBalance))
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WithdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DepositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TransferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(ViewAccountLabel1)
                    .addContainerGap(441, Short.MAX_VALUE)))
        );

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new java.awt.CardLayout());

        ViewPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("View All Account");

        AccountInfo.setColumns(20);
        AccountInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AccountInfo.setForeground(new java.awt.Color(0, 0, 0));
        AccountInfo.setRows(5);
        jScrollPane1.setViewportView(AccountInfo);

        javax.swing.GroupLayout ViewPanelLayout = new javax.swing.GroupLayout(ViewPanel);
        ViewPanel.setLayout(ViewPanelLayout);
        ViewPanelLayout.setHorizontalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        ViewPanelLayout.setVerticalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        MainPanel.add(ViewPanel, "card5");

        WithdrawPanel.setBackground(new java.awt.Color(255, 255, 255));

        CalculatorTxtField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CalculatorTxtField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CalculatorTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorTxtFieldActionPerformed(evt);
            }
        });

        nine.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        EnterButton.setText("Enter");
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        eight.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        seven.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        six.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        two.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        one.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        four.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        three.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        zero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Withdraw");

        javax.swing.GroupLayout WithdrawPanelLayout = new javax.swing.GroupLayout(WithdrawPanel);
        WithdrawPanel.setLayout(WithdrawPanelLayout);
        WithdrawPanelLayout.setHorizontalGroup(
            WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithdrawPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(WithdrawPanelLayout.createSequentialGroup()
                        .addGroup(WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(WithdrawPanelLayout.createSequentialGroup()
                                .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(WithdrawPanelLayout.createSequentialGroup()
                                .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(WithdrawPanelLayout.createSequentialGroup()
                                .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(EnterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addComponent(CalculatorTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithdrawPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(21, 21, 21))
        );
        WithdrawPanelLayout.setVerticalGroup(
            WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithdrawPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(23, 23, 23)
                .addComponent(CalculatorTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EnterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        MainPanel.add(WithdrawPanel, "card4");

        DepositPanel.setBackground(new java.awt.Color(255, 255, 255));

        CalculatorTxtField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CalculatorTxtField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CalculatorTxtField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorTxtField2ActionPerformed(evt);
            }
        });

        nine2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nine2.setText("9");
        nine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine2ActionPerformed(evt);
            }
        });

        EnterButton2.setText("Enter");
        EnterButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButton2ActionPerformed(evt);
            }
        });

        ClearButton2.setText("Clear");
        ClearButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButton2ActionPerformed(evt);
            }
        });

        eight2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eight2.setText("8");
        eight2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eight2ActionPerformed(evt);
            }
        });

        seven2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seven2.setText("7");
        seven2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven2ActionPerformed(evt);
            }
        });

        six2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        six2.setText("6");
        six2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six2ActionPerformed(evt);
            }
        });

        two2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        two2.setText("2");
        two2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two2ActionPerformed(evt);
            }
        });

        one2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        one2.setText("1");
        one2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one2ActionPerformed(evt);
            }
        });

        four2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        four2.setText("4");
        four2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four2ActionPerformed(evt);
            }
        });

        five2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        five2.setText("5");
        five2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five2ActionPerformed(evt);
            }
        });

        three2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        three2.setText("3");
        three2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three2ActionPerformed(evt);
            }
        });

        zero2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        zero2.setText("0");
        zero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Deposit");

        javax.swing.GroupLayout DepositPanelLayout = new javax.swing.GroupLayout(DepositPanel);
        DepositPanel.setLayout(DepositPanelLayout);
        DepositPanelLayout.setHorizontalGroup(
            DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CalculatorTxtField2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DepositPanelLayout.createSequentialGroup()
                        .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DepositPanelLayout.createSequentialGroup()
                                .addComponent(nine2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eight2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(seven2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(six2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DepositPanelLayout.createSequentialGroup()
                                .addComponent(five2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(four2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(three2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(two2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DepositPanelLayout.createSequentialGroup()
                                .addComponent(one2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(zero2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ClearButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(EnterButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DepositPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        DepositPanelLayout.setVerticalGroup(
            DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addComponent(CalculatorTxtField2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nine2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(five2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(zero2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(one2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ClearButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EnterButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        MainPanel.add(DepositPanel, "card4");

        TransferPanel.setBackground(new java.awt.Color(255, 255, 255));

        TransferAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        TransferNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Account Number");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Amount");

        ConfirmTransfer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConfirmTransfer.setText("Confirm");
        ConfirmTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmTransferActionPerformed(evt);
            }
        });

        ViewAccountLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ViewAccountLabel.setForeground(new java.awt.Color(0, 0, 0));
        ViewAccountLabel.setText("Transfer Amount");

        javax.swing.GroupLayout TransferPanelLayout = new javax.swing.GroupLayout(TransferPanel);
        TransferPanel.setLayout(TransferPanelLayout);
        TransferPanelLayout.setHorizontalGroup(
            TransferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferPanelLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(TransferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransferPanelLayout.createSequentialGroup()
                        .addComponent(ViewAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransferPanelLayout.createSequentialGroup()
                        .addGroup(TransferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ConfirmTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TransferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(TransferNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TransferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(105, 105, 105))))
        );
        TransferPanelLayout.setVerticalGroup(
            TransferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(ViewAccountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(TransferNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(TransferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ConfirmTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        MainPanel.add(TransferPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
//menu   
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
    JOptionPane.showMessageDialog(null, "Thank you for using bank system");
    dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed
    
    private void TransferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferButtonActionPerformed
        
        MainPanel.removeAll();
        MainPanel.add(TransferPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
        
    }//GEN-LAST:event_TransferButtonActionPerformed
    
    private void DepositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositButtonActionPerformed
        
        MainPanel.removeAll();
        MainPanel.add(DepositPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
        
    }//GEN-LAST:event_DepositButtonActionPerformed
    
    private void WithdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawButtonActionPerformed
        
        MainPanel.removeAll();
        MainPanel.add(WithdrawPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
        
    }//GEN-LAST:event_WithdrawButtonActionPerformed
//Withdraw
    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        CalculatorTxtField.setText(CalculatorTxtField.getText() + "0");
    }//GEN-LAST:event_zeroActionPerformed
    
    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        CalculatorTxtField.setText(CalculatorTxtField.getText() + "3");
    }//GEN-LAST:event_threeActionPerformed
    
    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        CalculatorTxtField.setText(CalculatorTxtField.getText() + "5");
    }//GEN-LAST:event_fiveActionPerformed
    
    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        CalculatorTxtField.setText(CalculatorTxtField.getText() + "4");
    }//GEN-LAST:event_fourActionPerformed
    
    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        CalculatorTxtField.setText(CalculatorTxtField.getText() + "1");
    }//GEN-LAST:event_oneActionPerformed
    
    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        CalculatorTxtField.setText(CalculatorTxtField.getText() + "2");
    }//GEN-LAST:event_twoActionPerformed
    
    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        CalculatorTxtField.setText(CalculatorTxtField.getText() + "6");
    }//GEN-LAST:event_sixActionPerformed
    
    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        CalculatorTxtField.setText(CalculatorTxtField.getText() + "7");
    }//GEN-LAST:event_sevenActionPerformed
    
    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        CalculatorTxtField.setText(CalculatorTxtField.getText() + "8");
    }//GEN-LAST:event_eightActionPerformed
    
    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        CalculatorTxtField.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed
    
    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed
        try {
            double withdrawAmount = Double.parseDouble(CalculatorTxtField.getText());
            
            if (withdrawAmount < 1) {
                JOptionPane.showMessageDialog(null, "Cannot withdraw an amount below 1");
            } else {
                String accountNumber = AccountNumber.getText();
                
                if (Menu.accounts.containsKey(accountNumber)) {
                    double currentBalance = Menu.accounts.get(accountNumber);
                    
                    if (withdrawAmount > currentBalance) {
                        JOptionPane.showMessageDialog(null, "Cannot withdraw because you do not have enough balance in your account");
                    } else {
                        double newBalance = currentBalance - withdrawAmount;
                        Menu.accounts.put(accountNumber, newBalance);
                        AccountNumberBalance.setText(Double.toString(newBalance));
                        
                        JOptionPane.showMessageDialog(null, "Withdrawal successful with the amount of $" + withdrawAmount);
                        JOptionPane.showMessageDialog(null, "New balance of your current account is $" + newBalance);
                        CalculatorTxtField.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid account number please check the account number and try again.");
                }
            }
        } catch (NumberFormatException e) {
            System.out.println("Invalid input. Please enter a valid number.");
            CalculatorTxtField.setText("");
        }
        
    }//GEN-LAST:event_EnterButtonActionPerformed
    
    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        CalculatorTxtField.setText(CalculatorTxtField.getText() + "9");
    }//GEN-LAST:event_nineActionPerformed
 
//deposit
    
    private void nine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine2ActionPerformed
        CalculatorTxtField2.setText(CalculatorTxtField2.getText() + "9");
    }//GEN-LAST:event_nine2ActionPerformed
    
    private void EnterButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButton2ActionPerformed
        try {
            double depositAmount = Double.parseDouble(CalculatorTxtField2.getText());
            
            if (depositAmount < 1) {
                JOptionPane.showMessageDialog(null, "Cannot deposit an amount below 1");
            } else {
                String accountNumber = AccountNumber.getText();
                
                if (Menu.accounts.containsKey(accountNumber)) {
                    double currentBalance = Menu.accounts.get(accountNumber);
                    double newBalance = currentBalance + depositAmount;
                    Menu.accounts.put(accountNumber, newBalance); 
                    
                    AccountNumberBalance.setText(Double.toString(newBalance));
                    JOptionPane.showMessageDialog(null, "Deposit successful with the amount of $" + depositAmount);
                    JOptionPane.showMessageDialog(null, "New balance of your current account is $" + newBalance);
                    CalculatorTxtField2.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid account number please check the account number and try again.");
                }
            }
        } catch (NumberFormatException e) {
            System.out.println("Invalid input. Please enter a valid number.");
            CalculatorTxtField.setText("");
        }
    }//GEN-LAST:event_EnterButton2ActionPerformed
    
    private void ClearButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButton2ActionPerformed
        CalculatorTxtField2.setText("");
    }//GEN-LAST:event_ClearButton2ActionPerformed
    
    private void eight2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eight2ActionPerformed
        CalculatorTxtField2.setText(CalculatorTxtField2.getText() + "8");
    }//GEN-LAST:event_eight2ActionPerformed
    
    private void seven2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven2ActionPerformed
        CalculatorTxtField2.setText(CalculatorTxtField2.getText() + "7");
    }//GEN-LAST:event_seven2ActionPerformed
    
    private void six2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six2ActionPerformed
        CalculatorTxtField2.setText(CalculatorTxtField2.getText() + "6");
    }//GEN-LAST:event_six2ActionPerformed
    
    private void two2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two2ActionPerformed
        CalculatorTxtField2.setText(CalculatorTxtField2.getText() + "2");
    }//GEN-LAST:event_two2ActionPerformed
    
    private void one2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one2ActionPerformed
        CalculatorTxtField2.setText(CalculatorTxtField2.getText() + "1");
    }//GEN-LAST:event_one2ActionPerformed
    
    private void four2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four2ActionPerformed
        CalculatorTxtField2.setText(CalculatorTxtField2.getText() + "4");
    }//GEN-LAST:event_four2ActionPerformed
    
    private void five2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five2ActionPerformed
        CalculatorTxtField2.setText(CalculatorTxtField2.getText() + "5");
    }//GEN-LAST:event_five2ActionPerformed
    
    private void three2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three2ActionPerformed
        CalculatorTxtField2.setText(CalculatorTxtField2.getText() + "3");
    }//GEN-LAST:event_three2ActionPerformed
    
    private void zero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero2ActionPerformed
        CalculatorTxtField2.setText(CalculatorTxtField2.getText() + "0");
    }//GEN-LAST:event_zero2ActionPerformed
    
    private void CalculatorTxtField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculatorTxtField2ActionPerformed
      
    }//GEN-LAST:event_CalculatorTxtField2ActionPerformed
    
    private void ConfirmTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmTransferActionPerformed
        try {
            double transferAmount = Double.parseDouble(TransferAmount.getText());
            String sourceAccountNumber = AccountNumber.getText();
            String destinationAccountNumber = TransferNumber.getText();
            
            if (destinationAccountNumber.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill out the transfer account number");
                return;
            }
            
            if (sourceAccountNumber.equals(destinationAccountNumber)) {
                JOptionPane.showMessageDialog(null, "Cannot transfer to the same account");
                return;
            }
            
            if (transferAmount < 1) {
                JOptionPane.showMessageDialog(null, "Cannot transfer an amount below 1");
                return;
            }
            
            boolean sourceIsAccountOne = sourceAccountNumber.equals("123456789");
            boolean sourceIsAccountTwo = sourceAccountNumber.equals("987654321");
            boolean destinationIsAccountOne = destinationAccountNumber.equals("123456789");
            boolean destinationIsAccountTwo = destinationAccountNumber.equals("987654321");
            
            if (!(sourceIsAccountOne || sourceIsAccountTwo)) {
                JOptionPane.showMessageDialog(null, "Invalid source account number");
                return;
            }
            
            if (!(destinationIsAccountOne || destinationIsAccountTwo)) {
                JOptionPane.showMessageDialog(null, "Invalid destination account number");
                return;
            }
            
            double sourceAccountBalance = accounts.get(sourceAccountNumber);
            double destinationAccountBalance = accounts.get(destinationAccountNumber);
            
            if (transferAmount > sourceAccountBalance) {
                JOptionPane.showMessageDialog(null, "Cannot transfer because you do not have enough balance in your account");
                return;
            }
            
            sourceAccountBalance -= transferAmount;
            destinationAccountBalance += transferAmount;
            
            accounts.put(sourceAccountNumber, sourceAccountBalance);
            accounts.put(destinationAccountNumber, destinationAccountBalance);
            
            AccountNumberBalance.setText(Double.toString(sourceAccountBalance));
            
            JOptionPane.showMessageDialog(null, "Transfer successful with the amount of $" + transferAmount);
            JOptionPane.showMessageDialog(null, "New balance of your current account is $" + sourceAccountBalance);
            TransferAmount.setText("");
            TransferNumber.setText("");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input please enter a valid number.");
        }
    }//GEN-LAST:event_ConfirmTransferActionPerformed
    
    private void CalculatorTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculatorTxtFieldActionPerformed
        
    }//GEN-LAST:event_CalculatorTxtFieldActionPerformed

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        MainPanel.removeAll();
        MainPanel.add(ViewPanel);
        MainPanel.repaint();
        MainPanel.revalidate();    
        
        
        StringBuilder output = new StringBuilder("Account Details\n");
        for (Map.Entry<String, Double> entry : accounts.entrySet()) {
            output.append("Account Number: ").append(entry.getKey()).append("   Balance: $").append(entry.getValue()).append("\n");
        }
        AccountInfo.setText(output.toString());
        
    }//GEN-LAST:event_ViewButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountBalanceLabel;
    private javax.swing.JTextArea AccountInfo;
    public static javax.swing.JLabel AccountNumber;
    public static javax.swing.JLabel AccountNumberBalance;
    public static javax.swing.JTextField CalculatorTxtField;
    public static javax.swing.JTextField CalculatorTxtField2;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ClearButton2;
    private javax.swing.JButton ConfirmTransfer;
    public static javax.swing.JButton DepositButton;
    private javax.swing.JPanel DepositPanel;
    private javax.swing.JButton EnterButton;
    private javax.swing.JButton EnterButton2;
    public static javax.swing.JButton ExitButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField TransferAmount;
    public static javax.swing.JButton TransferButton;
    private javax.swing.JTextField TransferNumber;
    private javax.swing.JPanel TransferPanel;
    private javax.swing.JLabel ViewAccountLabel;
    private javax.swing.JLabel ViewAccountLabel1;
    private javax.swing.JButton ViewButton;
    private javax.swing.JPanel ViewPanel;
    public static javax.swing.JButton WithdrawButton;
    private javax.swing.JPanel WithdrawPanel;
    private javax.swing.JButton eight;
    private javax.swing.JButton eight2;
    private javax.swing.JButton five;
    private javax.swing.JButton five2;
    private javax.swing.JButton four;
    private javax.swing.JButton four2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nine;
    private javax.swing.JButton nine2;
    private javax.swing.JButton one;
    private javax.swing.JButton one2;
    private javax.swing.JButton seven;
    private javax.swing.JButton seven2;
    private javax.swing.JButton six;
    private javax.swing.JButton six2;
    private javax.swing.JButton three;
    private javax.swing.JButton three2;
    private javax.swing.JButton two;
    private javax.swing.JButton two2;
    private javax.swing.JButton zero;
    private javax.swing.JButton zero2;
    // End of variables declaration//GEN-END:variables
}
