
import java.awt.Color;
import javax.swing.JOptionPane;

/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
*/

/**
 *
 * @author rhed
 */

/** try {
 * Login Login = new Login();
 * Menu Menu = new Menu();
 * String AccountNumber = Login.AccountNumber.getText();
 *
 * double totalAmount = Menu.totalAmount();
 * double AccountNum = Double.parseDouble(TransferAccountNum.getText());
 * double transferAmount = Double.parseDouble(TransferAmount.getText());
 *
 *
 * if (TransferAccountNum.getText().equals("")) {
 * JOptionPane.showMessageDialog(null, "Please fill out the transfer Account Number");
 *
 * }else if (AccountNumber.equals(TransferAccountNum)){
 * JOptionPane.showMessageDialog(null, "Cannot transfer to the same account");
 * } else if (transferAmount < 1) {
 * JOptionPane.showMessageDialog(null, "Cannot Transfer amount of below 1");
 * }else if(transferAmount > totalAmount){
 * JOptionPane.showMessageDialog(null, "Cannot transfer because you do not have enough balance in your account");
 * } else if(TransferAccountNum.getText().contains("987654321") || TransferAccountNum.getText().contains("123456789") ){
 * JOptionPane.showMessageDialog(null, "A amount of "+ transferAmount);
 *
 * } else {
 * JOptionPane.showMessageDialog(null, "Incorrect Username or Password");
 * }
 * } catch (Exception e) {
 *
 * JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
 * } */


public class TransferFunction extends javax.swing.JFrame {
    
    /**
     * Creates new form Transfer_Function
     */
    public TransferFunction() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TransferAccountNum = new javax.swing.JTextField();
        TransferAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Transfer Funds");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Account Number");

        TransferAccountNum.setText("Enter Account Number");
        TransferAccountNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TransferAccountNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TransferAccountNumFocusLost(evt);
            }
        });

        TransferAmount.setText("Enter Amount");
        TransferAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TransferAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TransferAmountFocusLost(evt);
            }
        });
        TransferAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferAmountActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Amount");

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TransferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TransferAccountNum, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TransferAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TransferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BackButton)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            String accountNumber = Login.AccountNumber.getText();
            String transferAccountNum = TransferAccountNum.getText();
            double transferAmount = Double.parseDouble(TransferAmount.getText());
            
            
            double totalAmount = Menu.totalAmount();
            
            
            if (transferAccountNum.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill out the transfer account number");
            } else if (accountNumber.equals(transferAccountNum)) {
                JOptionPane.showMessageDialog(null, "Cannot transfer to the same account");
            } else if (transferAmount < 1) {
                JOptionPane.showMessageDialog(null, "Cannot transfer an amount below 1");
            } else if (transferAmount > totalAmount) {
                JOptionPane.showMessageDialog(null, "Cannot transfer because you do not have enough balance in your account");
            } else if (transferAccountNum.contains("987654321") || transferAccountNum.contains("123456789")) {
                totalAmount -= transferAmount;
                JOptionPane.showMessageDialog(null, "Transfer successful with the Amount of " + transferAmount);
                JOptionPane.showMessageDialog(null, "New Amount of your current account is " + totalAmount);
                
            } else {
                
                JOptionPane.showMessageDialog(null, "Account not found or invalid");
            }
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(null, "Invalid input: Please enter valid numbers");
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void TransferAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransferAmountActionPerformed
    
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        Menu Menu = new Menu();
        Menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed
    
    private void TransferAccountNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TransferAccountNumFocusGained
        if(TransferAccountNum.getText().equals("Enter Account Number")){
            
            TransferAccountNum.setText("");
            TransferAccountNum.setForeground(new Color(0,0,0));
            
        }
    }//GEN-LAST:event_TransferAccountNumFocusGained
    
    private void TransferAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TransferAmountFocusLost
        if(TransferAmount.getText().equals("")){
            
            TransferAmount.setText("Enter Amount");
            TransferAmount.setForeground(new Color(70,73,75));
        }        
    }//GEN-LAST:event_TransferAmountFocusLost
    
    private void TransferAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TransferAmountFocusGained
        if(TransferAmount.getText().equals("Enter Amount")){
            
            TransferAmount.setText("");
            TransferAmount.setForeground(new Color(0,0,0));
            
        }
    }//GEN-LAST:event_TransferAmountFocusGained
    
    private void TransferAccountNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TransferAccountNumFocusLost
        if(TransferAccountNum.getText().equals("")){
            
            TransferAccountNum.setText("Enter Account Number");
            TransferAccountNum.setForeground(new Color(70,73,75));
        }
    }//GEN-LAST:event_TransferAccountNumFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferFunction().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField TransferAccountNum;
    private javax.swing.JTextField TransferAmount;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
